# Generated by Django 4.2.6 on 2023-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationEventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('vip_price', models.FloatField(default=0.0)),
                ('general_price', models.FloatField(default=0.0)),
                ('location', models.CharField(default='No location mentioned', max_length=255)),
                ('duration_mins', models.IntegerField(default=10)),
                ('time', models.CharField(default='10:00 AM', max_length=30)),
            ],
        ),
    ]
