# Generated by Django 4.2.6 on 2023-10-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationeventmodel',
            name='time',
            field=models.CharField(default='10:00 AM', max_length=30),
        ),
    ]
