# Generated by Django 4.2.6 on 2023-10-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationNotificationsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('rsvped', models.BooleanField(default=False)),
                ('attended', models.BooleanField(default=False)),
                ('bought_vip', models.BooleanField(default=True)),
                ('qr_image', models.ImageField(blank=True, max_length=800, null=True, upload_to='images/')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.plantationeventmodel')),
            ],
        ),
    ]
