# Generated by Django 4.2.6 on 2023-10-22 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_plantationproduct_discount_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=255)),
                ('street_name', models.CharField(max_length=255)),
                ('street_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlantationCardInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('cvc', models.IntegerField()),
                ('expiry_year', models.IntegerField(default=2023)),
                ('expiry_month', models.CharField(default='Jan', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PlantationOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('cellphone', models.CharField(default='031253551', max_length=11)),
                ('email', models.EmailField(default='name@company.com', max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.plantationaddress')),
                ('card_information', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.plantationcardinformation')),
                ('products', models.ManyToManyField(to='main.plantationproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
