# Generated by Django 4.2.6 on 2023-10-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rent_price', models.FloatField(default=0.0)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=1)),
                ('discount_percentage', models.IntegerField(default=0)),
                ('tax_percentage', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='services.plantationservice')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
