# Generated by Django 4.2.6 on 2023-10-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationImageVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.AddField(
            model_name='plantationproduct',
            name='image',
            field=models.ImageField(default='image.pnj', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='plantationproduct',
            name='variations',
            field=models.ManyToManyField(blank=True, to='products.plantationimagevariation'),
        ),
    ]
