# Generated by Django 4.2.6 on 2023-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_plantationproduct_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationproduct',
            name='row_number',
            field=models.CharField(default='M2', max_length=50),
        ),
        migrations.AddField(
            model_name='plantationproduct',
            name='shelf_number',
            field=models.CharField(default='R1', max_length=50),
        ),
    ]
