# Generated by Django 4.2.6 on 2023-10-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.plantationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PlantationCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_items', models.IntegerField(blank=True, default=0, null=True)),
                ('total_price', models.FloatField(blank=True, default=0.0, null=True)),
                ('items', models.ManyToManyField(blank=True, to='cart.plantationproductdetails')),
            ],
        ),
    ]
