# Generated by Django 4.2.6 on 2023-10-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationcartmodel',
            name='items',
            field=models.ManyToManyField(blank=True, to='cart.plantationproductdetails'),
        ),
    ]
