# Generated by Django 4.2.6 on 2023-10-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_plantationcartmodel_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationcartmodel',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantationcartmodel',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
    ]
