# Generated by Django 4.2.6 on 2023-10-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_plantationcartmodel_total_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationcartmodel',
            name='total_items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='plantationcartmodel',
            name='total_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
