# Generated by Django 4.2.6 on 2023-10-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationAppointmentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('appointment_done', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('location', models.CharField(default='Cape town offices', max_length=255)),
            ],
        ),
    ]
