# Generated by Django 4.2.6 on 2023-10-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationservice',
            name='image',
            field=models.ImageField(default='image.png', upload_to='services/'),
        ),
    ]
