# Generated by Django 4.2.6 on 2023-10-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantationuser',
            name='as_admin',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
