# Generated by Django 4.2.6 on 2023-10-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_plantationuser_as_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantationuser',
            name='as_admin',
            field=models.CharField(blank=True, default=' ', max_length=20, null=True),
        ),
    ]
