# Generated by Django 4.2.6 on 2023-10-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_ordered', models.IntegerField(default=0)),
                ('items_recieved', models.IntegerField(default=0)),
                ('items_broken', models.IntegerField(default=0)),
                ('item_price', models.FloatField(default=0.0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.plantationproduct')),
            ],
        ),
        migrations.CreateModel(
            name='PlantationSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=200)),
                ('provice', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PlantationSupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='suppliers.plantationproductinfo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='suppliers.plantationsupplier')),
            ],
        ),
        migrations.AddField(
            model_name='plantationproductinfo',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.plantationsupplier'),
        ),
    ]
